name: 'Gotify Notification'
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Gotify Notification
      uses: eikendev/gotify-action@master
      with:
        gotify_api_base: '${{ secrets.gotify_api_base }}'
        gotify_app_token: '${{ secrets.gotify_app_token }}'
        notification_title: 'Build Complete'
        notification_message: 'Your build was completed.'